os:
  - linux

dist: bionic

env:
  matrix:
    # cmake test
    - TASK=cmake_test
    # python test
    - TASK=python_test

before_install:
  # Configure Intel and Microsoft APT repositories
  - sudo apt-get -q update
  - echo 'deb [arch=amd64] https://download.01.org/intel-sgx/sgx_repo/ubuntu bionic main' | sudo tee /etc/apt/sources.list.d/intel-sgx.list
  - wget -qO - https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key | sudo apt-key add -
  - echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-7 main" | sudo tee /etc/apt/sources.list.d/llvm-toolchain-bionic-7.list
  - wget -qO - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - echo "deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main" | sudo tee /etc/apt/sources.list.d/msprod.list
  - wget -qO - https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - sudo apt-get -qq update
  # Install dependencies
  - sudo apt -y install clang-7 libssl-dev gdb libsgx-enclave-common libsgx-enclave-common-dev libprotobuf10 libsgx-dcap-ql libsgx-dcap-ql-dev az-dcap-client open-enclave=0.17.1 libmbedtls-dev
  - wget https://github.com/Kitware/CMake/releases/download/v3.15.6/cmake-3.15.6-Linux-x86_64.sh
  - sudo bash cmake-3.15.6-Linux-x86_64.sh --skip-license --prefix=/usr/local
  - export PATH=/usr/local:/usr/local/bin:$PATH 
  # Setup OE environment variables
  - source /opt/openenclave/share/openenclave/openenclaverc
  # Append to $PYTHONPATH
  - if [ "${TASK}" != "python_sdist_test" ]; then export PYTHONPATH=${PYTHONPATH}:${PWD}/python-package; fi
  - export PYTHONPATH=${PYTHONPATH}:${PWD}/tests/python

install:
  - source tests/travis/setup.sh

script:
  - tests/travis/run_test.sh

#cache:
#  directories:
#    - ${HOME}/.cache/usr
#    - ${HOME}/.cache/pip

#before_cache:
#  - dmlc-core/scripts/travis/travis_before_cache.sh
#
#after_failure:
#  - tests/travis/travis_after_failure.sh
#
after_success:
   - bash <(curl -s https://codecov.io/bash) -a '-o src/ src/*.c'

#notifications:
#  email:
#    on_success: change
#    on_failure: always
